name: Doxygen Generate & Deploy

on: 
  push:
    branches: [ master ]

jobs:
  doxygen:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      
      - name: Get doxygen
        run: sudo apt-get install doxygen -y
        
      - name: Build doxyfile
        uses: mattnotmitt/doxygen-action@v1.9.2
        with:
          working-directory: '.'
          doxyfile-path: './Doxyfile'

      - name: Deploy documentation to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './doxygen_doc/html'

