name: Static-Code-Analysis

on:
  push:
    # pushes to master
    branches: [ master ]
  pull_request:
    # PRs to master
    branches: [ master ]

# abort old runs if a new one is started
concurrency:
  group: ${{ github.head_ref }}-tests
  cancel-in-progress: true

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run static code analysis script
        run: ./checks/run-staticAnalysis.sh $PWD
